"""Static salary data for the 2025 season.

Two distinct things live here:

1. DEFAULT salary tables (rank -> salary). These are the authoritative tables
   from LEAGUE_MECHANICS.md §12 and drive the post-race salary adjustment
   engine (issue 3B). Do not edit — they encode the published formula.

2. The 2025 starting grid ranking. Per §12.5 starting salaries are a manual,
   staff-set input (prior season + testing + projection), not generated by the
   formula. We approximate them by ranking the grid and reading the default
   table at each rank.

   ⚠️  REVIEW BEFORE PRODUCTION SEEDING. The orderings below are best-effort
   and the driver_number → driver mapping must be confirmed against the actual
   2025 entry list. Reorder these lists to set starting salaries; the team
   names must match OpenF1's `team_name` strings exactly or the fallback applies.
"""

# --- Authoritative default tables (LEAGUE_MECHANICS.md §12) -----------------
# Drivers: 1st = £34M, −£1.6M per rank, floor £400k at P22.
DRIVER_DEFAULT_SALARY = {
    1: 34_000_000, 2: 32_400_000, 3: 30_800_000, 4: 29_200_000,
    5: 27_600_000, 6: 26_000_000, 7: 24_400_000, 8: 22_800_000,
    9: 21_200_000, 10: 19_600_000, 11: 18_000_000, 12: 16_400_000,
    13: 14_800_000, 14: 13_200_000, 15: 11_600_000, 16: 10_000_000,
    17: 8_400_000, 18: 6_800_000, 19: 5_200_000, 20: 3_600_000,
    21: 2_000_000, 22: 400_000,
}

# Constructors: 1st = £30M, −£2.6M per rank, floor £4M at P11.
CONSTRUCTOR_DEFAULT_SALARY = {
    1: 30_000_000, 2: 27_400_000, 3: 24_800_000, 4: 22_200_000,
    5: 19_600_000, 6: 17_000_000, 7: 14_400_000, 8: 11_800_000,
    9: 9_200_000, 10: 6_600_000, 11: 4_000_000,
}

DRIVER_SALARY_FLOOR = DRIVER_DEFAULT_SALARY[22]
CONSTRUCTOR_SALARY_FLOOR = CONSTRUCTOR_DEFAULT_SALARY[11]

# --- 2025 starting grid (EDITABLE — see warning above) ----------------------
# Team names ordered by approximate 2025 constructor standing.
CONSTRUCTOR_2025_RANKING = [
    "McLaren",
    "Ferrari",
    "Mercedes",
    "Red Bull Racing",
    "Williams",
    "Aston Martin",
    "Kick Sauber",
    "Racing Bulls",
    "Haas F1 Team",
    "Alpine",
]

# Driver numbers ordered by approximate 2025 driver standing.
DRIVER_2025_RANKING = [
    1,    # Verstappen
    4,    # Norris
    81,   # Piastri
    16,   # Leclerc
    63,   # Russell
    44,   # Hamilton
    12,   # Antonelli
    23,   # Albon
    18,   # Stroll
    14,   # Alonso
    10,   # Gasly
    31,   # Ocon
    27,   # Hülkenberg
    87,   # Bearman
    22,   # Tsunoda
    30,   # Lawson
    5,    # Bortoleto
    6,    # Hadjar
    43,   # Colapinto
    55,   # Sainz
]


def starting_driver_salary(driver_number: int) -> int:
    """Starting salary for a driver by their 2025 grid rank, floor otherwise."""
    if driver_number in DRIVER_2025_RANKING:
        rank = DRIVER_2025_RANKING.index(driver_number) + 1
        return DRIVER_DEFAULT_SALARY.get(rank, DRIVER_SALARY_FLOOR)
    return DRIVER_SALARY_FLOOR


def starting_constructor_salary(team_name: str) -> int:
    """Starting salary for a team by its 2025 rank, floor otherwise."""
    if team_name in CONSTRUCTOR_2025_RANKING:
        rank = CONSTRUCTOR_2025_RANKING.index(team_name) + 1
        return CONSTRUCTOR_DEFAULT_SALARY.get(rank, CONSTRUCTOR_SALARY_FLOOR)
    return CONSTRUCTOR_SALARY_FLOOR
