"""initial schema

Revision ID: 3edaa5134da6
Revises: 
Create Date: 2026-06-02 14:16:40.349436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edaa5134da6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('salary', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'season', name='uq_constructor_season')
    )
    with op.batch_alter_table('constructors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constructors_season'), ['season'], unique=False)

    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('circuit', sa.String(), nullable=True),
    sa.Column('total_laps', sa.Integer(), nullable=True),
    sa.Column('has_sprint', sa.Boolean(), nullable=False),
    sa.Column('lockdown_at', sa.DateTime(), nullable=True),
    sa.Column('meeting_key', sa.Integer(), nullable=True),
    sa.Column('quali_session_key', sa.Integer(), nullable=True),
    sa.Column('sprint_session_key', sa.Integer(), nullable=True),
    sa.Column('race_session_key', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', name='uq_race_season_round')
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_races_season'), ['season'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('constructor_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('quali_pos', sa.Integer(), nullable=True),
    sa.Column('race_pos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'constructor_id', name='uq_constructor_result')
    )
    with op.batch_alter_table('constructor_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constructor_results_constructor_id'), ['constructor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_constructor_results_race_id'), ['race_id'], unique=False)

    op.create_table('constructor_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('quali_pts', sa.Integer(), nullable=False),
    sa.Column('race_pts', sa.Integer(), nullable=False),
    sa.Column('total_pts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'constructor_id', name='uq_constructor_score')
    )
    with op.batch_alter_table('constructor_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constructor_scores_constructor_id'), ['constructor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_constructor_scores_race_id'), ['race_id'], unique=False)

    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_number', 'season', name='uq_driver_number_season')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_constructor_id'), ['constructor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_season'), ['season'], unique=False)

    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leagues_invite_code'), ['invite_code'], unique=True)

    op.create_table('magic_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_magic_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('salary_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_type', sa.Enum('DRIVER', 'CONSTRUCTOR', name='elementtype', native_enum=False, length=16), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('salary_before', sa.BigInteger(), nullable=False),
    sa.Column('salary_after', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_history_race_id'), ['race_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('element_type', sa.Enum('DRIVER', 'CONSTRUCTOR', name='elementtype', native_enum=False, length=16), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('race_start', sa.Integer(), nullable=False),
    sa.Column('contract_length', sa.Integer(), nullable=False),
    sa.Column('signed_salary', sa.BigInteger(), nullable=False),
    sa.Column('released_early', sa.Boolean(), nullable=False),
    sa.Column('released_at_race', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_user_id'), ['user_id'], unique=False)

    op.create_table('driver_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('quali_pos', sa.Integer(), nullable=True),
    sa.Column('sprint_pos', sa.Integer(), nullable=True),
    sa.Column('race_pos', sa.Integer(), nullable=True),
    sa.Column('laps_completed', sa.Integer(), nullable=False),
    sa.Column('dnf', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_driver_result')
    )
    with op.batch_alter_table('driver_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_results_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_results_race_id'), ['race_id'], unique=False)

    op.create_table('driver_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('quali_pts', sa.Integer(), nullable=False),
    sa.Column('sprint_pts', sa.Integer(), nullable=False),
    sa.Column('race_pts', sa.Integer(), nullable=False),
    sa.Column('overtake_pts', sa.Integer(), nullable=False),
    sa.Column('improvement_pts', sa.Integer(), nullable=False),
    sa.Column('teammate_pts', sa.Integer(), nullable=False),
    sa.Column('completion_pts', sa.Integer(), nullable=False),
    sa.Column('total_pts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_driver_score')
    )
    with op.batch_alter_table('driver_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_scores_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_scores_race_id'), ['race_id'], unique=False)

    op.create_table('fantasy_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_id', 'race_id', name='uq_fantasy_score')
    )
    with op.batch_alter_table('fantasy_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fantasy_scores_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_scores_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_scores_user_id'), ['user_id'], unique=False)

    op.create_table('league_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_balance', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_league_member')
    )
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_members_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_league_members_league_id'))

    op.drop_table('league_members')
    with op.batch_alter_table('fantasy_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fantasy_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_fantasy_scores_race_id'))
        batch_op.drop_index(batch_op.f('ix_fantasy_scores_league_id'))

    op.drop_table('fantasy_scores')
    with op.batch_alter_table('driver_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_scores_race_id'))
        batch_op.drop_index(batch_op.f('ix_driver_scores_driver_id'))

    op.drop_table('driver_scores')
    with op.batch_alter_table('driver_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_results_race_id'))
        batch_op.drop_index(batch_op.f('ix_driver_results_driver_id'))

    op.drop_table('driver_results')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_user_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_league_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('salary_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_history_race_id'))

    op.drop_table('salary_history')
    with op.batch_alter_table('magic_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_magic_tokens_token_hash'))

    op.drop_table('magic_tokens')
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_invite_code'))

    op.drop_table('leagues')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_season'))
        batch_op.drop_index(batch_op.f('ix_drivers_constructor_id'))

    op.drop_table('drivers')
    with op.batch_alter_table('constructor_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constructor_scores_race_id'))
        batch_op.drop_index(batch_op.f('ix_constructor_scores_constructor_id'))

    op.drop_table('constructor_scores')
    with op.batch_alter_table('constructor_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constructor_results_race_id'))
        batch_op.drop_index(batch_op.f('ix_constructor_results_constructor_id'))

    op.drop_table('constructor_results')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_races_season'))

    op.drop_table('races')
    with op.batch_alter_table('constructors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constructors_season'))

    op.drop_table('constructors')
    # ### end Alembic commands ###
